### ISSUE TITLE
Module00

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/Team02-Module00#5]
# EPIC

- [ ] SEAME-pt/Team02-WarmUp#18 

# Description

This introductory module guides students through foundational tasks and programming exercises designed to familiarize them with the SEA
ecosystem, GitHub workflow, Qt framework, and basic C++ programming skills.

## TASKS

- [x] SEAME-pt/Team02-Module00#2
- [x] SEAME-pt/Team02-Module00#3 
- [x] SEAME-pt/Team02-Module00#4 
- [ ] SEAME-pt/Team02-Module00#1
